version: '3.8'

services:
  mswd-abuyog:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mswd-abuyog
    container_name: mswd-abuyog
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
    ports:
      - 5173:5173  # Vite frontend dev server
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: mswd-abuyogdb
      DB_USERNAME: smct
      DB_PASSWORD: smct
    networks:
      - mswd-abuyog-server

  mswd-abuyog-nginx:
    image: nginx:alpine
    container_name: mswd-abuyog-nginx
    restart: unless-stopped
    ports:
      - 1005:80  # Serve Laravel app via Nginx
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mswd-abuyog
    networks:
      - mswd-abuyog-server

networks:
  mswd-abuyog-server:
    driver: bridge
