services:
  mswd-abuyog:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mswd-abuyog
    container_name: mswd-abuyog
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/nginx.conf


    networks:
      - mswd-abuyog-server
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1  # Replace with your host's IP if necessary
      DB_PORT: 3306
      DB_DATABASE: mswd-abuyogdb
      DB_USERNAME: smct
      DB_PASSWORD: smct 
    # deploy:
    #   replicas: 3  # Set the desired number of replicas

  mswd-abuyog-nginx:
    image: nginx:alpine
    container_name: mswd-abuyog-nginx
    restart: unless-stopped
    ports:
      - 1005:1005
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./docker-compose/nginx/default.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    networks:
      - mswd-abuyog-server

networks:
  mswd-abuyog-server:
    driver: bridge
