services:
  mswd-abuyog:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mswd-abuyog
    container_name: mswd-abuyog
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1  # Replace with your host's IP if necessary
      DB_PORT: 3306
      DB_DATABASE: mswd_abuyogdb
      DB_USERNAME: smct
      DB_PASSWORD: smct 
